### ISSUE TITLE
Error parsing javascript data to dart data in onMessage event

### ISSUE THREAD

**Issue by Kaysen98** [GaspardMerten/Firebase-Cloud-Messaging-Interop#4]
Hello 👍 

Im glad Ive found your project, because I was having problems implementing FCM for Flutter web :)

But Ive run into an error: When I use the onMessage Event, there is always this error:

![image](https://user-images.githubusercontent.com/72981948/96264171-35781180-0fc4-11eb-9cdf-553ad871d44b.png)

Are you able to fix it, I have literally implemented it like this:

![image](https://user-images.githubusercontent.com/72981948/96264264-4b85d200-0fc4-11eb-8c3b-a48650ac475f.png)

When im not setting the onMessage listener, the push notification appears, but I want to grab the data in the application as well.

Thank you :)

**Comment by GaspardMerten** [comment]
Hello,

Please update to 1.2.1 and tell me if your issue is resolved!

**Comment by GaspardMerten** [comment]
__
